CREATE TABLE EMPLOYEE(
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    salary INT,
    PRIMARY KEY (id)
);
INSERT INTO EMPLOYEE(name, salary)
VALUES ('VENKAT',99999);
INSERT INTO EMPLOYEE(name, salary)
VALUES ('SAI',95000);
INSERT INTO EMPLOYEE(name, salary)
VALUES ('SAIRAM',90000);